-- MySQL Script generated by MySQL Workbench
-- Mit 28 Mär 2018 14:17:04 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PinApp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PinApp` ;

-- -----------------------------------------------------
-- Schema PinApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PinApp` DEFAULT CHARACTER SET utf8 ;
USE `PinApp` ;

-- -----------------------------------------------------
-- Table `PinApp`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`user` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `number of pins` INT UNSIGNED,
  `number of pinboards` INT UNSIGNED,
  `number of followers` INT,
  `number of users being followed` INT,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'maintains user details, note that isAdmin is Boolean with Tinyint data type - by default user has only user privileges ',
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `PinApp`.`topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`topics` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`topics` (
  `name` VARCHAR(255) NOT NULL,
  `save_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`name`));


-- -----------------------------------------------------
-- Table `PinApp`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`notification` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`notification` (
  `email` VARCHAR(255) NOT NULL,
  `pin_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`email`, `user_email`),
  INDEX `fk_notification_user_idx` (`user_email` ASC),
  CONSTRAINT `fk_notification_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `PinApp`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PinApp`.`user_follows_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`user_follows_user` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`user_follows_user` (
  `follower` VARCHAR(255) NOT NULL,
  `person being followed` VARCHAR(255) NOT NULL,
  `isPermitted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`follower`, `person being followed`),
  INDEX `fk_user_has_user_user2_idx` (`person being followed` ASC),
  INDEX `fk_user_has_user_user1_idx` (`follower` ASC),
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`follower`)
    REFERENCES `PinApp`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`person being followed`)
    REFERENCES `PinApp`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PinApp`.`pinboards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`pinboards` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`pinboards` (
  `name` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isPrivate` TINYINT(1) NOT NULL DEFAULT 0,
  `user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`, `user_email`),
  INDEX `fk_pinboards_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_pinboards_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `PinApp`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PinApp`.`user_follows_pinboards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`user_follows_pinboards` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`user_follows_pinboards` (
  `user_email` VARCHAR(255) NOT NULL,
  `pinboards_name` VARCHAR(255) NOT NULL,
  `pinboards_user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_email`, `pinboards_name`, `pinboards_user_email`),
  INDEX `fk_user_has_pinboards_pinboards1_idx` (`pinboards_name` ASC, `pinboards_user_email` ASC),
  INDEX `fk_user_has_pinboards_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_user_has_pinboards_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `PinApp`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_pinboards_pinboards1`
    FOREIGN KEY (`pinboards_name` , `pinboards_user_email`)
    REFERENCES `PinApp`.`pinboards` (`name` , `user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PinApp`.`pins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`pins` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`pins` (
  `name` VARCHAR(255) NOT NULL,
  `update_time` TIMESTAMP NULL,
  `save_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `images` VARCHAR(45) NOT NULL,
  `pinboards_name` VARCHAR(255) NOT NULL,
  `pinboards_user_email` VARCHAR(255) NOT NULL,
  `topics_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pinboards_name`, `pinboards_user_email`, `topics_name`),
  INDEX `fk_pins_topics1_idx` (`topics_name` ASC),
  CONSTRAINT `fk_pins_pinboards1`
    FOREIGN KEY (`pinboards_name` , `pinboards_user_email`)
    REFERENCES `PinApp`.`pinboards` (`name` , `user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pins_topics1`
    FOREIGN KEY (`topics_name`)
    REFERENCES `PinApp`.`topics` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PinApp`.`user_has_pins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`user_has_pins` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`user_has_pins` (
  `user_email` VARCHAR(255) NOT NULL,
  `pins_pinboards_name` VARCHAR(255) NOT NULL,
  `pins_pinboards_user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_email`, `pins_pinboards_name`, `pins_pinboards_user_email`),
  INDEX `fk_user_has_pins_pins1_idx` (`pins_pinboards_name` ASC, `pins_pinboards_user_email` ASC),
  INDEX `fk_user_has_pins_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_user_has_pins_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `PinApp`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_pins_pins1`
    FOREIGN KEY (`pins_pinboards_name` , `pins_pinboards_user_email`)
    REFERENCES `PinApp`.`pins` (`pinboards_name` , `pinboards_user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PinApp`.`admin_create_or_update_topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PinApp`.`admin_create_or_update_topics` ;

CREATE TABLE IF NOT EXISTS `PinApp`.`admin_create_or_update_topics` (
  `user_email` VARCHAR(255) NOT NULL,
  `topics_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_email`, `topics_name`),
  INDEX `fk_user_has_topics_topics1_idx` (`topics_name` ASC),
  INDEX `fk_user_has_topics_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_user_has_topics_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `PinApp`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_topics_topics1`
    FOREIGN KEY (`topics_name`)
    REFERENCES `PinApp`.`topics` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
